import { LabelPreset } from '../types/inventory';

// ==========================================
// 1. 애니라벨 (AnyLabel) 17종 규격
// ==========================================
export const ANYLABEL_PRESETS: LabelPreset[] = [
  // 1. 우편 및 물류/택배 발송용 (대·중형 라벨)
  {
    id: 'any_v3110',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3110 (1칸)',
    labelsCount: 1,
    widthMm: 210.0,
    heightMm: 297.0,
    marginLeftMm: 0.0,
    marginTopMm: 0.0,
    gapXMm: 0.0,
    gapYMm: 0.0,
    cols: 1,
    rows: 1,
    layout: 'portrait',
    description: 'A4 전면 스티커, 박스 부착용 대형 안내문',
  },
  {
    id: 'any_v3120',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3120 (2칸)',
    labelsCount: 2,
    widthMm: 210.0,
    heightMm: 148.5,
    marginLeftMm: 0.0,
    marginTopMm: 0.0,
    gapXMm: 0.0,
    gapYMm: 0.0,
    cols: 1,
    rows: 2,
    layout: 'portrait',
    description: '대형 택배 박스 안내문, 물류 파레트 표기',
  },
  {
    id: 'any_v3220',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3220 (8칸)',
    labelsCount: 8,
    widthMm: 99.1,
    heightMm: 67.7,
    marginLeftMm: 4.6,
    marginTopMm: 13.1,
    gapXMm: 2.6,
    gapYMm: 0.0,
    cols: 2,
    rows: 4,
    layout: 'portrait',
    description: '대봉투 주소, 택배 송장 대체용, 박스 내용물 표시',
  },
  {
    id: 'any_v3230',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3230 (14칸)',
    labelsCount: 14,
    widthMm: 99.1,
    heightMm: 38.1,
    marginLeftMm: 4.6,
    marginTopMm: 15.2,
    gapXMm: 2.6,
    gapYMm: 0.0,
    cols: 2,
    rows: 7,
    layout: 'portrait',
    description: '일반 편지·서류 봉투 수신/발신 주소용 (가장 대중적)',
  },
  {
    id: 'any_v3240',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3240 (16칸)',
    labelsCount: 16,
    widthMm: 99.1,
    heightMm: 33.9,
    marginLeftMm: 4.6,
    marginTopMm: 12.9,
    gapXMm: 2.6,
    gapYMm: 0.0,
    cols: 2,
    rows: 8,
    layout: 'portrait',
    description: '소형 봉투 주소 라벨, 화일철 겉면 분류',
  },
  {
    id: 'any_v3250',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3250 (18칸)',
    labelsCount: 18,
    widthMm: 63.5,
    heightMm: 46.6,
    marginLeftMm: 7.2,
    marginTopMm: 8.7,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 6,
    layout: 'portrait',
    description: '소형 소포, 다목적 물품 라벨',
  },
  {
    id: 'any_v3260',
    brand: 'AnyLabel',
    category: '애니라벨 1. 우편·물류용 (대·중형)',
    modelName: 'V3260 (21칸)',
    labelsCount: 21,
    widthMm: 63.5,
    heightMm: 38.1,
    marginLeftMm: 7.2,
    marginTopMm: 15.2,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 7,
    layout: 'portrait',
    description: 'DM 발송, 제품 박스 기본 식별표',
  },

  // 2. 파일 정리 및 바코드/재고 관리용 (중·소형 라벨)
  {
    id: 'any_v3310',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3310 (24칸)',
    labelsCount: 24,
    widthMm: 63.5,
    heightMm: 33.9,
    marginLeftMm: 7.2,
    marginTopMm: 12.9,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 8,
    layout: 'portrait',
    description: '부품 상자 라벨, 제품 바코드 및 가격표',
  },
  {
    id: 'any_v3410',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3410 (40칸)',
    labelsCount: 40,
    widthMm: 47.0,
    heightMm: 26.9,
    marginLeftMm: 8.0,
    marginTopMm: 14.0,
    gapXMm: 4.0,
    gapYMm: 0.0,
    cols: 4,
    rows: 10,
    layout: 'portrait',
    description: '소형 바코드, 유통기한/로트 번호 표기',
  },
  {
    id: 'any_v3430',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3430 (44칸)',
    labelsCount: 44,
    widthMm: 48.3,
    heightMm: 25.4,
    marginLeftMm: 5.0,
    marginTopMm: 8.8,
    gapXMm: 2.8,
    gapYMm: 0.0,
    cols: 4,
    rows: 11,
    layout: 'portrait',
    description: '소형 부품함 라벨, 상품 QR코드',
  },
  {
    id: 'any_v3610',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3610 (54칸)',
    labelsCount: 54,
    widthMm: 26.0,
    heightMm: 29.5,
    marginLeftMm: 16.0,
    marginTopMm: 15.75,
    gapXMm: 5.6,
    gapYMm: 0.0,
    cols: 6,
    rows: 9,
    layout: 'portrait',
    description: '소형 바코드, 전자 부품 식별 태그 (6열×9행)',
  },
  {
    id: 'any_v3520',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3520 (60칸)',
    labelsCount: 60,
    widthMm: 38.1,
    heightMm: 19.2,
    marginLeftMm: 4.7,
    marginTopMm: 4.5,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 5,
    rows: 15,
    layout: 'portrait',
    description: '미니 바코드, 자재 코드 라벨 (5열×15행)',
  },
  {
    id: 'any_v3510',
    brand: 'AnyLabel',
    category: '애니라벨 2. 파일·바코드·재고관리용 (중·소형)',
    modelName: 'V3510 (65칸)',
    labelsCount: 65,
    widthMm: 38.1,
    heightMm: 21.2,
    marginLeftMm: 4.7,
    marginTopMm: 10.7,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 5,
    rows: 13,
    layout: 'portrait',
    description: '정밀 바코드, 소형 패키지 가격표 (5열×13행)',
  },

  // 3. 인덱스 및 견출/특수 표기용 (소형·특수 라벨)
  {
    id: 'any_v3580',
    brand: 'AnyLabel',
    category: '애니라벨 3. 인덱스·견출·특수용 (소형)',
    modelName: 'V3580 (81칸)',
    labelsCount: 81,
    widthMm: 55.0,
    heightMm: 10.0,
    marginLeftMm: 17.5,
    marginTopMm: 13.5,
    gapXMm: 5.0,
    gapYMm: 0.0,
    cols: 3,
    rows: 27,
    layout: 'portrait',
    description: '화일철 인덱스 탭, 파일 바인더 측면 네임택',
  },
  {
    id: 'any_v3420',
    brand: 'AnyLabel',
    category: '애니라벨 3. 인덱스·견출·특수용 (소형)',
    modelName: 'V3420 (84칸)',
    labelsCount: 84,
    widthMm: 46.0,
    heightMm: 11.1,
    marginLeftMm: 6.0,
    marginTopMm: 8.0,
    gapXMm: 4.0,
    gapYMm: 2.0,
    cols: 4,
    rows: 21,
    layout: 'portrait',
    description: '얇은 파일철 인덱스, 견출지 대체',
  },
  {
    id: 'any_v3530',
    brand: 'AnyLabel',
    category: '애니라벨 3. 인덱스·견출·특수용 (소형)',
    modelName: 'V3530 (96칸)',
    labelsCount: 96,
    widthMm: 30.0,
    heightMm: 14.0,
    marginLeftMm: 8.0,
    marginTopMm: 16.5,
    gapXMm: 4.0,
    gapYMm: 2.5,
    cols: 6,
    rows: 16,
    layout: 'portrait',
    description: '서류 인덱스, 장비 버튼/단자 식별 표기',
  },
  {
    id: 'any_v3560',
    brand: 'AnyLabel',
    category: '애니라벨 3. 인덱스·견출·특수용 (소형)',
    modelName: 'V3560 (189칸)',
    labelsCount: 189,
    widthMm: 25.4,
    heightMm: 10.0,
    marginLeftMm: 5.6,
    marginTopMm: 13.5,
    gapXMm: 2.0,
    gapYMm: 0.0,
    cols: 7,
    rows: 27,
    layout: 'portrait',
    description: '초소형 네임택, 전선/케이블 마킹용 (7열×27행)',
  },
];

// ==========================================
// 2. 폼텍 (Formtec) 18종 공식 정밀 규격
// ==========================================
export const FORMTEC_PRESETS: LabelPreset[] = [
  {
    id: 'formtec_3130',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3130 (1칸)',
    labelsCount: 1,
    widthMm: 210.0,
    heightMm: 297.0,
    marginLeftMm: 0.0,
    marginTopMm: 0.0,
    gapXMm: 0.0,
    gapYMm: 0.0,
    cols: 1,
    rows: 1,
    layout: 'portrait',
    description: 'A4 전면 스티커, 대형 안내문',
  },
  {
    id: 'formtec_3120',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3120 (2칸)',
    labelsCount: 2,
    widthMm: 199.6,
    heightMm: 143.5,
    marginLeftMm: 5.2,
    marginTopMm: 5.0,
    gapXMm: 0.0,
    gapYMm: 0.0,
    cols: 1,
    rows: 2,
    layout: 'portrait',
    description: '물류 파레트, 대형 박스 표기 (1열×2행)',
  },
  {
    id: 'formtec_3118',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3118 (4칸)',
    labelsCount: 4,
    widthMm: 99.1,
    heightMm: 139.0,
    marginLeftMm: 4.7,
    marginTopMm: 9.5,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 2,
    rows: 2,
    layout: 'portrait',
    description: '물류 박스용, 중형 패키지',
  },
  {
    id: 'formtec_3116',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3116 (6칸)',
    labelsCount: 6,
    widthMm: 99.1,
    heightMm: 93.1,
    marginLeftMm: 4.7,
    marginTopMm: 8.8,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 2,
    rows: 3,
    layout: 'portrait',
    description: '제품 식별표, 물류 관리',
  },
  {
    id: 'formtec_3114',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3114 (8칸)',
    labelsCount: 8,
    widthMm: 99.1,
    heightMm: 67.7,
    marginLeftMm: 4.7,
    marginTopMm: 13.1,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 2,
    rows: 4,
    layout: 'portrait',
    description: '대봉투 주소, 택배 박스 발송용',
  },
  {
    id: 'formtec_3112',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3112 (12칸)',
    labelsCount: 12,
    widthMm: 63.5,
    heightMm: 72.0,
    marginLeftMm: 7.2,
    marginTopMm: 4.5,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 4,
    layout: 'portrait',
    description: '물품 분류, 박스 내용물 표기',
  },
  {
    id: 'formtec_3105',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3105 (14칸)',
    labelsCount: 14,
    widthMm: 99.1,
    heightMm: 38.1,
    marginLeftMm: 4.7,
    marginTopMm: 15.2,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 2,
    rows: 7,
    layout: 'portrait',
    description: '편지·서류봉투 주소용 (가장 대중적)',
  },
  {
    id: 'formtec_3107',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3107 (16칸)',
    labelsCount: 16,
    widthMm: 99.1,
    heightMm: 33.9,
    marginLeftMm: 4.7,
    marginTopMm: 12.9,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 2,
    rows: 8,
    layout: 'portrait',
    description: '우편 주소용, 서류철 분류',
  },
  {
    id: 'formtec_3109',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3109 (18칸)',
    labelsCount: 18,
    widthMm: 63.5,
    heightMm: 46.6,
    marginLeftMm: 7.2,
    marginTopMm: 8.7,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 6,
    layout: 'portrait',
    description: '소형 소포, 다목적 물품 라벨',
  },
  {
    id: 'formtec_3108',
    brand: 'Formtec',
    category: '폼텍(Formtec) 1. 물류·우편용 (대·중형)',
    modelName: 'Formtec 3108 (21칸)',
    labelsCount: 21,
    widthMm: 63.5,
    heightMm: 38.1,
    marginLeftMm: 7.2,
    marginTopMm: 15.2,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 3,
    rows: 7,
    layout: 'portrait',
    description: 'DM 발송, 제품 박스 식별',
  },

  // 2. 바코드 및 재고관리용 (중·소형)
  {
    id: 'formtec_3106',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3106 (24칸)',
    labelsCount: 24,
    widthMm: 64.0,
    heightMm: 34.0,
    marginLeftMm: 6.5,
    marginTopMm: 12.5,
    gapXMm: 3.0,
    gapYMm: 0.0,
    cols: 3,
    rows: 8,
    layout: 'portrait',
    description: '바인더 인덱스, 부품 박스 라벨',
  },
  {
    id: 'formtec_3102',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3102 (40칸)',
    labelsCount: 40,
    widthMm: 47.0,
    heightMm: 26.9,
    marginLeftMm: 8.0,
    marginTopMm: 14.0,
    gapXMm: 4.0,
    gapYMm: 0.0,
    cols: 4,
    rows: 10,
    layout: 'portrait',
    description: '소형 바코드, 유통기한/로트 번호',
  },
  {
    id: 'formtec_3104',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3104 (44칸)',
    labelsCount: 44,
    widthMm: 48.5,
    heightMm: 25.4,
    marginLeftMm: 4.7,
    marginTopMm: 8.8,
    gapXMm: 3.0,
    gapYMm: 0.0,
    cols: 4,
    rows: 11,
    layout: 'portrait',
    description: '부품 상자 라벨, 상품 QR코드',
  },
  {
    id: 'formtec_3610',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3610 (54칸)',
    labelsCount: 54,
    widthMm: 26.0,
    heightMm: 29.5,
    marginLeftMm: 16.0,
    marginTopMm: 15.75,
    gapXMm: 5.6,
    gapYMm: 0.0,
    cols: 6,
    rows: 9,
    layout: 'portrait',
    description: '전자 부품 태그, 소형 바코드',
  },
  {
    id: 'formtec_3101',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3101 (60칸)',
    labelsCount: 60,
    widthMm: 38.1,
    heightMm: 19.2,
    marginLeftMm: 4.7,
    marginTopMm: 4.5,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 5,
    rows: 12,
    layout: 'portrait',
    description: '소형 바코드, 자재 코드',
  },
  {
    id: 'formtec_3100',
    brand: 'Formtec',
    category: '폼텍(Formtec) 2. 바코드·부품재고용 (중·소형)',
    modelName: 'Formtec 3100 (65칸)',
    labelsCount: 65,
    widthMm: 38.1,
    heightMm: 21.2,
    marginLeftMm: 4.7,
    marginTopMm: 10.7,
    gapXMm: 2.5,
    gapYMm: 0.0,
    cols: 5,
    rows: 13,
    layout: 'portrait',
    description: '정밀 바코드, 소형 패키지 가격표',
  },

  // 3. 인덱스 및 특수/원형 라벨
  {
    id: 'formtec_3621',
    brand: 'Formtec',
    category: '폼텍(Formtec) 3. 인덱스·특수·원형 라벨',
    modelName: 'Formtec 3621 (36칸)',
    labelsCount: 36,
    widthMm: 95.0,
    heightMm: 14.0,
    marginLeftMm: 6.0,
    marginTopMm: 12.5,
    gapXMm: 8.0,
    gapYMm: 2.0,
    cols: 2,
    rows: 18,
    layout: 'portrait',
    description: '파일 바인더 측면 인덱스 라벨',
  },
  {
    id: 'formtec_3640',
    brand: 'Formtec',
    category: '폼텍(Formtec) 3. 인덱스·특수·원형 라벨',
    modelName: 'Formtec 3640 (12칸 원형)',
    labelsCount: 12,
    widthMm: 63.5,
    heightMm: 63.5,
    marginLeftMm: 7.2,
    marginTopMm: 14.5,
    gapXMm: 2.5,
    gapYMm: 6.5,
    cols: 3,
    rows: 4,
    layout: 'portrait',
    shape: 'circle',
    description: '원형 네임택, 포장 밀봉 스티커 (지름 63.5mm)',
  },
];

// ==========================================
// 3. 일반 랙 라벨 (재단/코팅용)
// ==========================================
export const GENERAL_PRESETS: LabelPreset[] = [
  {
    id: 'rack_a4_9',
    brand: 'General',
    category: '4. 일반 랙 라벨 (재단/코팅용)',
    modelName: 'A4 가로 3×3 (9칸)',
    labelsCount: 9,
    widthMm: 80.0,
    heightMm: 60.0,
    marginLeftMm: 15.0,
    marginTopMm: 10.0,
    gapXMm: 8.0,
    gapYMm: 5.0,
    cols: 3,
    rows: 3,
    layout: 'landscape',
    description: '표준 랙 부착용 (코팅 후 재단에 최적화)',
  },
  {
    id: 'rack_a4_8',
    brand: 'General',
    category: '4. 일반 랙 라벨 (재단/코팅용)',
    modelName: 'A4 세로 2×4 (8칸)',
    labelsCount: 8,
    widthMm: 80.0,
    heightMm: 60.0,
    marginLeftMm: 15.0,
    marginTopMm: 15.0,
    gapXMm: 10.0,
    gapYMm: 8.0,
    cols: 2,
    rows: 4,
    layout: 'portrait',
    description: '표준 랙 부착용 (A4 세로 방향)',
  },
];

export const ALL_LABEL_PRESETS: LabelPreset[] = [
  ...ANYLABEL_PRESETS,
  ...FORMTEC_PRESETS,
  ...GENERAL_PRESETS,
];

export function findPresetById(id?: string): LabelPreset | undefined {
  if (!id) return undefined;
  return ALL_LABEL_PRESETS.find((p) => p.id === id);
}

export function getPresetGroups(): Record<string, LabelPreset[]> {
  const groups: Record<string, LabelPreset[]> = {};
  ALL_LABEL_PRESETS.forEach((preset) => {
    if (!groups[preset.category]) {
      groups[preset.category] = [];
    }
    groups[preset.category].push(preset);
  });
  return groups;
}

export function getPresetsByBrand(brand: 'AnyLabel' | 'Formtec' | 'General' | 'ALL'): LabelPreset[] {
  if (brand === 'ALL') return ALL_LABEL_PRESETS;
  return ALL_LABEL_PRESETS.filter((p) => p.brand === brand);
}
